import React from 'react'
import './AboutFnp.css'

export default function AboutFnp() {
    return (
        <article>
            <div class="aboutfnp-content">
                <h2>Send Flowers Online with Ferns N Petals (FNP): India's Biggest Florist Chain</h2>
                <p>For over 25 years, Ferns N Petals is helping you to celebrate your special moments by delivering fresh flowers and fabulous gifts to your loved ones. Ferns N Petals was established in 1994 and
        <a href="/flower-bouquets">flower bouquet delivery</a> was the first and only thing that we were doing. From there on, FNP grew to what it is today including the current gifting options that feature the choicest
        <a href="/personalised-gifts">personalized gifts</a>, cakes, chocolates along with artificial flowers fresh cut flowers and flower basket. From just 1 flower shop in Delhi during 1994, Ferns N Petals is now
        <strong>the largest florist chain</strong> with more than 300+ stores (and still counting) across all the major cities and towns of India. Along with the widest distribution network, our strong physical &amp; online presence makes us the best choice to send flowers &amp; gifts for deliveries across India and around the globe. The remarkable distribution network of FNP and the sheer number of retail stores that we have, is something no other online florist and
        <strong>gift delivery service in India</strong> can boast about and this is one of the biggest factors that differentiates us from the competition. We bank upon the smiles of our 6 million happy customers with the quality of service and consistency of service delivery provided across India and abroad. With your trust invested in our brand, Ferns N Petals is the largest floral and gifting brand in India and abroad. Our master florists expert have quite brilliantly concocted love and emotions together to roll out the best gifts for all occasions.
        </p>
                <h2>International Presence</h2>
                <p>After having established ourselves as market leaders in India, Ferns N Petals has expanded its international footprints into the South East Asia and Middle East. In addition to a physical presence, with two stores in UAE and one in Singapore, we also have built a strong online presence with separate websites in Qatar and Saudi Arabia. You can check out our websites catering to different regions; <a href="https://www.fnp.ae/">www.fnp.ae</a> in UAE, <a href="https://www.fnp.sg/">www.fnp.sg</a> in Singapore, <a href="https://qa.fnp.com/">qa.fnp.com</a> in Qatar, and <a href="https://sa.fnp.com/">sa.fnp.com</a> in Saudi Arabia.</p>
                <h2>Same Day Flower Delivery - in 2 Hours or even less!</h2>
                <p>People say that we have gotten 25 years older but our creative think tanks are growing younger with each passing day. Inspired by the current trends, we keep coming up with new floral arrangements &amp; gifts for almost every emotion, celebration and occasion. With our aim to ‘wow’ our customers and delivering smiles, we have added a little something that goes into making every 'delivery' special. We understand the importance of delivering the gifts on time or before time therefore we deliver flowers, flower baskets and other items at the doorstep of your loved ones with lightning speed in the shortest possible time - as fast as 2 Hours of ordering. This helps us to deliver fresh flowers every time you order a bouquet. We are committed to exceed your expectations whenever you order for a simple bouquet of flowers or an exquisite flower arrangement of exotic flowers. We understand the surprise element and emotional connection to the order and hence strive hard to deliver it with love and care. At Ferns N Petals,
        <strong>online flower delivery</strong> happens to destinations all over India and abroad. If you are planning to order flowers online and you want the same day delivery of
        <a href="/flowers/delhi">flowers to Delhi</a> or looking for online flower delivery in Mumbai or bouquet delivery in Mumbai by the best
        <a href="/flowers/mumbai">florist in Mumbai</a>, Bangalore, Hyderabad or any other city of India, FNP is the ideal choice. Ferns N Petals is the
        <strong>only online flower shop</strong> that has a real florist network across India that actually differentiates us from other so-called online florists who work with third party florists for their deliveries.
        </p>
                <h2>Expert Florists Curating the Perfect Flower Bouquets</h2>
                <p>The presence of flowers is enough to make any occasion or moment truly a memorable affair. Flowers can make an ordinary room extremely beautiful. Flowers are widely used in decorations, as gifts, or even as ornaments on various dresses. People can explore a variety of fresh vibrant flowers such as roses, tulips, orchids, carnations, sunflowers, chrysanthemums and a lot more through the help of our online gifting store. All these beautiful flowers will be delivered at your desired destination in blooming condition only. With an unmatched beauty and fragrance, these gorgeous and lovely flowers can easily mesmerise any individual in an effortless manner.</p>
                <p>Apart from the bouquet of flowers, our expert florists can create stunning floral arrangements that can be gifted to your loved ones on any special occasion or moments. These scintillating flowers are readily available in multiple colours, varieties and arrangements so that you can offer the best to your loved ones. We can help you deliver the beautiful bunch of fresh flower</p>
                <h2>Create Colorful Memories with Our Spectacular Birthday Cakes and Gifts</h2>
                <p>Undoubtedly, a birthday is the most important day in anyone’s life. All the great stories, journey, and adventures started due to this auspicious day. This is a day that is marked with great excitement and gifts form a major part of this occasion. A cake forms the most important part of a birthday celebration. So, if you want to send a lovely “Happy Birthday” wish to your best friend or close relative, you cannot ignore the wonderful
        <a href="/cakes/birthday">birthday cakes</a>. Unleash a delicious world of cream cakes, fondant cakes, semi-fondant cakes, tier cakes, designer cakes, and photo cakes only at Ferns N Petals. These cakes are available in a variety of flavors like chocolate, vanilla, butterscotch, mango, strawberry, red velvet, white forest, coffee, tiramisu, etc. You can opt for a midnight delivery of cake to your sweetheart’s doorstep and shower immense love, care, and affection which he/she would remember forever. Life is all about these happy moments where you live a little more. So, opt for these mesmerizing cakes as
        <a href="/gifts/birthday">birthday gifts</a> for your loved ones and enhance the bank of great memories.
        </p>
                <h2>Wide Variety of Fresh Cut Flowers For Every Occasion</h2>
                <p>Whenever you think about flowers, for most of us, Roses pop in our heads and we imagine a floral arrangement consisting of roses. And rightly so, Roses are the top selling cut flowers at Ferns N Petals in India and abroad because of the sheer popularity they carry. However apart from roses, we also deliver a wide variety of cut flowers viz., Lilies (second most popular flower at Ferns N Petals after roses), Carnations, Orchids, Gerberas, Daisies and other seasonal cut flowers &amp; imported cut flowers like Tulips.</p>
                <p>All the fresh cut flowers are delivered fresh to the customers in the form and design that they request. We have the cut flowers in wide variety of forms and designs including bouquets &amp; bunches, flower arrangements, etc. When it comes to flower bouquets, they are available in different designs &amp; wrappings including cello &amp; colorful paper wrappings. At Ferns N Petals, we discourage people from ordering cello wrapped bouquets because they are not environment-friendly. When it comes to flower arrangements, they are available as vase arrangements, basket arrangements potted arrangements or boxed arrangements while each of these containers also are available in wide variety of colors &amp; designs to suit varied requirements of our customers.</p>
                <h2>Adding more to Flowers - One Stop Shop for All Gifting Needs</h2>
                <p>While Ferns N Petals is the largest florist chain in India for over 2 decades now, it has stepped into gifting beyond flowers and now dominates the gifting industry in India. Ferns N Petals has now gone beyond just being a florist and is undertaking
        <a href="/cakes">online cake delivery</a> and also catering to beyond the floral gifting needs on special occasions – whether it is Valentine gifts, Rakhi Gifts for Raksha Bandhan, Mother's Day, Diwali or Bhai Dooj. Sending flowers and gifts with the Ferns N Petals is now just a click away. With our services, you can also
        <strong>send flowers to India from USA</strong>, or from other countries viz: UK, Australia or from any part of the world within a short time of just 2 Hours of ordering either on the website, android mobile app, iOS app and over the phone. At Ferns N Petals, we know that we are delivering emotions to the loved ones and also understand that timely delivery is a must in making those moments memorable. We go all the way to make sure that when you buy flowers online from Ferns N Petals, they are delivered on time, that you choose upon checkout. We also provide custom delivery services such as midnight delivery and also take up fixed time delivery besides the same day flower delivery for all occasions. You can send flowers to Mumbai,
        <a href="/gifts/delhi">
                        <strong>gifts to Delhi</strong>
                    </a>, Mumbai, Bangalore, Kolkata and other cities &amp; town across India and worldwide.
        </p>
                <h2>Order Impressive Women's Day Presents from Ferns N Petals</h2>
                <p>International Women's Day is celebrated to honour every woman for her accomplishments no matter how big or small they may be. This day commemorates the hard work and sacrifices made by women in their day to day life. Ferns N Petals is a reputable online store that provides an enormous array of Women's Day gift ideas that will make every woman feel special. Whether you buy a present for your mother, wife, sister, friend or daughter, it should be as beautiful and extraordinary as the woman. Take our pick from the gorgeous flower arrangements, personalised items, luscious cakes, fancy hampers, air-purifying plants, lip-smacking chocolates and plenty more options. If you are looking for unique gifts to express your gratitude to your mom or wife, take a look at the <a href="/gifts/womens-day">gifts for womens day</a> collection. From booking a guitarist, singer to recorded celebrity messages, we have it all. Choose any gift item and pair it with another to make exciting combos like a flower and chocolate, plant and cake, cushion and mug and several more. Ferns N Petals offers highly reliable and swift online delivery services like one hour, same day and midnight for all Women’s Day presents across multiple cities in India.</p>
                <h2>Send Holi Presents to your Near &amp; Dear Ones</h2>
                <p>Holi is one of the most joyous Hindu festivals as it commemorates the return of spring. The festival will be celebrated on 29th March. It is observed with vibrant colours, water guns, delectable sweets and massive gatherings. Friends and family greet each other with love as they spend the day playing and laughing. This day is also observed by gifting one and another beautiful and delicious presents. So this year, wish your loved ones a happy Holi with wonderful gifts from Ferns N Petals. On our website, you will come across a vast array of <a href="/gifts/holi">Holi gifts</a> that are suitable for people belonging to different age groups. These hampers consist of savoury chocolates, colours, water guns, flowers and a lot more items. When it comes to the traditional <a href="/sweets/holi">Holi Sweets</a>, no store is better than us. We have a huge range of gujiyas, ladoos, Soan Papdi, Kaju katli and several more sweets. If you wish to stray from the traditional gifts, you can opt for personalised gifts with quirky texts on cushions and adorable photos printed on mugs. We also have a lovely collection of indoor and outdoor plants that contain various health benefit qualities. Ferns N Petals is an esteemed online store serving customers top-notch quality products. Take your pick from any of these amazing gift items for a fun-loving and memorable celebration.</p>
                <h2>Send Digital Gifts to Your Loved Ones on Special Occasions</h2>
                <p>Exchanging gifts on special occasions is an age-old trend. With time, the tradition of gifting has evolved a lot.
        <a href="/digital-gifts">Digital gifts</a>are the new cool thing in town. These technology-enabled gifts are designed to make special occasions like birthday &amp; anniversary memorable. You can send digital gifts to your friends and family who are miles apart and put an instant smile on their faces. Ferns N Petals presents a variety of digital gift options, such as guitarist on call, personalised app, celebrity video messages, personalised e-books, e-greeting cards, digital caricatures, personalised video messages, and fitness on call. With these digital gifts, you can surprise your near and dear ones and make them feel closer through the virtual world of the Internet. You can give your partner a musical surprise on your wedding anniversary through a WhatsApp Video Conference call where the guitarist will play the songs of their choice. The personalised e-books would be an excellent option to delight your little ones on their birthday. You can also avail celebrity video message option available on our website to give a lovely surprise to your special one &amp; leave them star-struck. All the digital gifts are delivered online through video calls, SMS, or via email, so you don’t have to worry about their timely shipping.
        </p>
                <h2>Find The Most Stunning Gifts For Men &amp; Women Only at Ferns N Petals</h2>
                <p>Gifts constitute a large part of all our happy festivals and occasions. Ferns N Petals is the number online gift portal where you will find a large collection of gifts for both men and women and for every special day in your life. To impress the pretty and precious girls/women in your life, you can explore our amazing range of flower bouquets, chocolate baskets, designer cakes, spa materials, cosmetics hamper, jewelry items, handbags, soft toys, etc. While as
        <a href="/gifts/for-him">gifts for men</a>, we have the smart combo of belt &amp; wallet, combo of personalized mugs &amp; chocolates, basket or tray of dry fruits, personalized mobile phone covers, personalized lamp, sunglasses, grooming kit consisting of beard oil, face wash, and shampoo, etc. As our services are available in more than 400 locations in India, you can enjoy a hassle-free delivery of these gifts for men or women using our same-day, midnight, &amp; next day delivery services. Spread more love &amp; happiness among your loved ones using the great gifts and services of Ferns N Petals.
        </p>
                <h2>Opt for Ferns N Petals for Timely Delivery in India &amp; Abroad</h2>
                <p>Ferns N Petals is the name of trust among millions of customers scattered all over India and abroad. With an innovative and classic gift ideas pertaining to all kinds of festivals and occasions – Ferns N Petals is generally the number one choice among people. This trust that the customers have on us makes us work harder and achieve new goals every day. So, you would experience a world-class delivery service and premium quality of products over here. We are never late when it comes to delivery of gifts to your loved ones. You can thus experience a super-fast express, same-day, midnight, next day, and standard time &amp; 2-hour delivery services in India. In India, we cater to more than 400 locations that include the megacities, big towns, and small villages. So, you can end your love to places like Mumbai, Delhi, Bengaluru, Kolkata, Jharsuguda, Bhopal, Kota, Udaipur, Meerut, etc. Similarly, our services are also available worldwide in 170 countries and we offer our same-day, next day, standard time delivery services to send gifts abroad.</p>
                <h2>Get International Delivery of Gifts to 100+ Countries</h2>
                <p>Ferns N Petals helps you deliver your gift to 100+ countries worldwide. We deliver to all major countries like USA, UK, Canada, Australia, New Zealand, UAE, Germany, Philippines, and Singapore etc. Your loved ones can be settled anywhere and you can use our services to greet them on their special days or occasions. A lot of times it is not possible for your loved ones to be with you on festivals like Diwali, Raksha Bandhan, New Year, Christmas etc. But you should not worry much because we are here to let this distance mitigate with our amazing international delivery services. If your loved one is seated in New York or New Jersey in USA, London in UK, Dubai, Sharjah or Abu Dhabi in UAE, you can send gifts like flowers, cakes, and other hampers internationally with a single click.</p>
                <p>Out of all kind of gifts we have, you would also believe that a flower is the most beautiful one. The amazing fragrance and the captivating look generally takes your breath away and when it come sot expression of true and deep love, there cannot be anything as alluring as a flower.&nbsp;So if you are looking for
        <a href="/singapore/flowers">flower delivery in Singapore</a> or any other place, you can send it easily using our convenient delivery options.
        </p>
                <h2>Wish Your Loved Ones Instantly with Ferns N Petals International Services</h2>
                <p>Suppose you want to surprise your sweetheart seated away from you in New York, USA on her birthday or on anniversary, the easiest way is to opt for our online gift delivery. Wide variety of fresh flowers, cakes, chocolates, and personalized gift items to delight your darling in a breath-taking manner. With&nbsp;
        <a href="/usa/flowers">same day flower delivery in USA</a>, UK, Canada, UAE, etc. you can instantly show your love to your better half. Same Day delivery is the best option when you have to say sorry, congratulate someone or say thank you.
        </p>
                <p>We have our serviceability in almost all happening metro cities of the world and thus reaching your distant people would be really easy for us. If we talk about Indians settled abroad then USA for sure is in the top 3 destinations. Whether it is for further studies, job movements, or marriage, a good number of Indians are there. Now you can
        <a href="/usa/gifts">send gifts to USA from India</a> for all major occasions and normal ones like birthdays, anniversaries etc. We would pack your emotions of love carefully and surprise your loved ones scattered across the globe.
        </p>
                <h3>Fresh &amp; Suggested Reads from our Blog</h3>
                <ul class="blogs">
                    <li><h6>Take a Look at Essential Grooming Hampers for Men</h6>
                        <p>It’s the 21st century and even men are peculiar about how they look and dress up. Men have...<a href="/blog/essential-grooming-hampers-for-men" target="_blank"> Read More...</a></p></li>
                    <li><h6>Which Aamir Khan’s Movie Character are You Based on Your Zodiac Sign?</h6>
                        <p>Ailla! Ae Kya Bolti Tu! Thinking about Aamir khan? Famed as the Perfectionist, he was born on...<a href="/blog/which-aamir-khans-movie-character-are-you-based-on-your-zodiac-sign" target="_blank"> Read More...</a></p></li>
                    <li><h6>6 Spectacular Gift Ideas for White Day</h6>
                        <p>Love can be expressed at any time. In February, we wonderfully celebrated Valentine’s Day. Are...<a href="/blog/6-spectacular-gift-ideas-for-white-day" target="_blank"> Read More...</a></p></li>
                </ul>
            </div>
        </article>
    )
}
